// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtS0aQZ0kubKkEU8mFSNr1hG50ekUqgS8',
    appId: '1:567544337295:web:1ad8429ccd8a32380f71fa',
    messagingSenderId: '567544337295',
    projectId: 'astrix-store',
    authDomain: 'astrix-store.firebaseapp.com',
    storageBucket: 'astrix-store.firebasestorage.app',
    measurementId: 'G-7RNB6D3PN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchC7mBL_DiVTYiH9H3ru82wRv-N60FBQ',
    appId: '1:567544337295:android:7f1e543c2a3415230f71fa',
    messagingSenderId: '567544337295',
    projectId: 'astrix-store',
    storageBucket: 'astrix-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyn6y4Rl3-UAj-4PP3-WWuXRWbFWlfoUs',
    appId: '1:567544337295:ios:1ebac7b758f8cf510f71fa',
    messagingSenderId: '567544337295',
    projectId: 'astrix-store',
    storageBucket: 'astrix-store.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
